# Базовые настройки сервера
server:
  port: 8080

# Настройки приложения
spring:
  application:
    name: api-gateway
  
  # Настройки Spring Cloud Gateway
  cloud:
    gateway:
      # Включение обнаружения сервисов
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      
      # Конфигурация маршрутов
      routes:
        # Маршрут к сервису заказов
        - id: supplier-service
          uri: lb://supplier-service
          predicates:
            - Path=/api/suppliers/**
          filters:
            - name: CircuitBreaker
              args:
                name: supplierCircuitBreaker
                fallbackUri: forward:/fallback/suppliers
        
        # Маршрут к сервису инвентаря
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
          filters:
            - name: CircuitBreaker
              args:
                name: inventoryCircuitBreaker
                fallbackUri: forward:/fallback/inventory
        
        # Маршрут для собственного API
        - id: api-gateway-controller
          uri: lb://api-gateway
          predicates:
            - Path=/api/composed-order/**

# Настройки Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      inventoryService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
      orderService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true

  retry:
    instances:
      inventoryService:
        maxAttempts: 2
        waitDuration: 100ms
        retryExceptions:
          - java.lang.IllegalStateException
          - java.io.IOException
          - org.springframework.web.client.ResourceAccessException
      orderService:
        maxAttempts: 2
        waitDuration: 100ms
        retryExceptions:
          - java.lang.IllegalStateException
          - java.io.IOException

# Настройки логирования
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG
    com.example.apigateway: DEBUG